language: python
python:
    - "3.5"
install:
    - pip install -r requirements.txt
    - pip install -r requirements/dev.txt
script:
    - pycodestyle src tests
    - pydocstyle src
    - python -m pytest tests/
