mqtt_host: "127.0.0.1"
mqtt_port: 1883

# Uncomment & add username & password for your mqtt broker if using
# mqtt_user:
# mqtt_pass:
#
root_topic: "/security/sensors/"

sensor_groups:
    example_group:
      - name: "sensor_a"
        type: "motion"
        pin: 7
      - name: "sensor_B"
        type: "door"
        pin: 8
    another_group:
      - name: "sensor_1"
        type: "window"
        pin: 9
