#!/bin/bash

echo -e "\n\nRunning linters"
echo -e "\n pycodestyle"
pycodestyle --count src
pycodestyle --count tests
echo -e "\n pydocstyle"
pydocstyle --count src
echo -e "\n\nRunning tests"
python3 -m pytest tests
